[package]
name = "tx_engine"
version = "0.1.0"
authors = ["james.meyer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { verson = "1.0.118", features = ["serde_derive"]}
csv = "1.1.5"